spring:
  application:
    name: challenge-service

  datasource:
    url: jdbc:mariadb://localhost:3306/aplazodb
    username: admin
    password: secretadmin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      initialization-fail-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8081

logging:
  level:
    root: WARN
