spring.application.name=costumer-service
server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/aplazodb
spring.datasource.username=admin
spring.datasource.password=secretadmin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect